---
- name: Set kibana_major_version
  set_fact: "kibana_major_version={{ kibana_version.split('.')[0] }}.x"
  when: kibana_major_version is undefined

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Copy Configuration File
  template:
    src: kibana.yml.j2
    dest: "{{ kibana_conf_dir }}/kibana.yml"
    owner: root
    group: "{{ kibana_group }}"
    mode: "0660"
    force: true
  notify: Restart kibana
